[package]
name = "pso2packetlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
serde = ["dep:serde"]

[dependencies]
aes = "0.8.2"
byteorder = "1.4.3"
cbc = "0.1.2"
hmac = "0.12.1"
rand = "0.8.5"
rc4 = "0.1.0"
rsa = "0.9.2"
serde = { version = "1.0.164", optional = true, features = ["derive"] }
sha2 = "0.10.7"
zstd = "0.12.3"
packetlib_impl = { path = "packetlib_impl" }

