[package]
name = "ppak_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
chrono = "0.4.38"
pso2packetlib = { path = "../..", features = ["ppac", "ngs_packets"] }
