[package]
name = "packetlib_impl"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.60", features = ["printing"] }
proc-macro2 = "1.0.81"
quote = "1.0.36"
